# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/mygui/Makefile 402736 2015-12-01 13:53:44Z amdmi3 $

PORTREVISION=	0
PKGNAMESUFFIX=	-dummy

COMMENT=	Dummy renderer for MyGUI

MASTERDIR=	${.CURDIR}/../mygui

MYGUI_RENDERSYSTEM=	1
MYGUI_SUBDIR=		Platforms/Dummy/DummyPlatform

.include "${MASTERDIR}/Makefile"
